---
title: "Investigación empírica y cuantitativa para la gestión pública"
output: html_document
---

Facultad de Derecho - UBA\
Maestría en Derecho y Gobierno\
2do bimestre 2026

Profesor: Demián Zayat\
dzayat@derecho.uba.ar

## Presentación

En la actualidad los datos y la información tienen una presencia constante en nuestras vidas. Tradicionalmente la capacidad de extraer información de los datos fue aprovechada por las corporaciones para tomar decisiones operativas y comerciales. Contar con datos y tener las capacidades para extraer información y tomar decisiones es una fuente de poder.

Los datos y la información pueden ser también utilizados para mejorar la vida de todas las personas, y para ello deben ser insumos para la implementación, monitoreo y evaluación de las políticas públicas. Producir datos de calidad y utilizarlos para gestionar políticas públicas son pasos fundamentales para mejorar la vida de las personas.

Para esto es necesario planificar la obtención de datos y el monitoreo y evaluación de sus resultados, para evaluar el impacto que tiene la política pública en la sociedad. Esto implica un cambio cultural sobre el modo en que se toman decisiones y se analizan las políticas públicas. Se trata, de este modo, de pasar de una visión puramente cualitativa del diseño de políticas a una visión mixta, que también involucra el análisis cuantitativo.

Sin embargo, no cualquier utilización o evaluación de datos responde a una visión igualitaria y democrática de la política pública. Podría suceder que sólo se garantice la eficiencia dejando de lado implicancias de justicia e igualdad. Por ello, la perspectiva de derechos humanos debe ser transversal al análisis de los procedimientos. No es solo una mayor eficiencia lo que debe buscar una perspectiva de datos en las políticas públicas. Asimismo, las políticas y usos de datos deben garantizar la protección de datos personales y el derecho a la privacidad.

En esta materia revisaremos qué implica utilizar una metodología cuantitativa o empírica para la determinación e implementación de las políticas públicas. Analizaremos las discusiones teóricas y prácticas sobre la toma de decisiones basadas en evidencias, y la utilidad que pueden tener los datos. Pensaremos cuáles son las consecuencias que la utilización masiva de datos puede tener sobre excluidos sociales o disidentes políticos.

Luego, pasaremos a una parte más práctica, sobre cómo realizar análisis desde los datos públicos, tanto de la EPH, como del Censo como de otras bases de datos públicas, que nos permitirán evaluar las políticas públicas de los últimos años. Para ello, esta materia aprenderemos diversas herramientas de la ciencia de datos para llevar adelante el análisis empírico. Para ello, deberemos aprender a utilizar software de análisis estadístico, y conoceremos el tipo de operaciones que puede hacerse para analizar y procesar datos. Con ayuda de la Inteligencia Artificial, llevaremos adelante estos análisis, por nuestra propia cuenta.

## Objetivos

El objetivo del curso es brindar herramientas metodológicas para poder planificar y evaluar una política pública basada en datos cuantitativos. Se espera que las y los alumnos puedan identificar las diversas metodologías de las ciencias sociales, cualitativas y cuantitativas, y puedan decidir cuál conviene utilizar en cada caso en la realización de una planificación, gestión y monitoreo de una política pública.

Al mismo tiempo, se espera que las y los alumnos cuenten con nociones básicas de la ciencia de datos, para analizar, procesar y graficar datos para la realización de informes.

## Metodología

En el curso se brindarán herramientas teóricas, y luego las utilizaremos de modo práctico. Para ello, además de las lecturas de la teoría, utilizaremos software para la ciencia de datos y aprenderemos a utilizarlo. Comenzamos con una introducción a la ciencia de datos, utilizando ejemplos jurídicos sencillos para familiarizarnos con la herramienta.

<u>**Se espera que antes del comienzo del curso las y los estudiantes hayan instalado en sus computadoras el software de fuente abierta R ([https://cran.r-project.org/](https://cran.r-project.org/)), el entorno RStudio para utilizarlo ([https://posit.co/products/open-source/rstudio/](https://posit.co/products/open-source/rstudio/)), y utilizaremos un manual para utilizarlo ([https://cdaj.netlify.app/](https://cdaj.netlify.app/)). Pueden conseguir un tutorial para la instalación [aquí](https://demzayat.github.io/derecho_y_datos/instalacion.html).**</u>

En una última etapa, juntaremos ambos saberes — la parte teórica sobre la toma de decisiones basadas en evidencia y la utilización de la Ciencia de Datos — para evaluar por nuestra cuenta el impacto del programa IFE implementado durante el 2020 en Argentina.

## Cronograma y bibliografía


### Clase 1. 2 de Julio.  Introducción a la metodología cuantitativa

Introducción a la metodología cuantitativa. Diferencias con investigaciones cualitativas. El Censo Nacional. Caso de Personas LGBT.

- Becket, [Datos, Pruebas e Ideas](https://drive.google.com/file/d/1qxKSvAcz6RUcT0K9W35X9mB77Nv2Zbzh/view?usp=sharing), capítulos 2 y 3: "Ideas, Opiniones y Pruebas" y "Cómo lo hacen los naturalistas", pp. 63 a 100.

- Becket, "Censos", pp. 110 a 150. Mismo [link](https://drive.google.com/file/d/1qxKSvAcz6RUcT0K9W35X9mB77Nv2Zbzh/view?usp=sharing)

- Pregunta sobre identidad de género en el CENSO 2022, [aca](https://drive.google.com/file/d/1VS33-QAdGdwflxa7gEp7Kw4Z9x8vhO9Q/view?usp=sharing).

### Feriado — 9 de Julio. Día de la Independencia. [Recuperamos como clase asincrónica]

### Clase 2. 16 de Julio.  Introducción a la ciencia de datos

- Sosa Escudero, [Big Data](https://drive.google.com/file/d/1N0-PntfrLKh-UNqEu9MexNwK8qvA0VAB/view?usp=sharing), Cap. 1 "Perdidos en el Océano de datos" y Cap. "Gran Hermano".

- Fundar, [Datos y Algoritmos para el desarrollo](https://drive.google.com/file/d/1r57K2u2w0FkQ71L_UrKM_YxNLLoW_xa5/view?usp=sharing), mayo 2021.

- Virginia Eubanks, [Automating Inequality](https://drive.google.com/file/d/1BBtL6Ze7NFvnFJ8fh8gcxFXqj7zm2AxA/view?usp=sharing), 2017, Smartins, cap. Introduction, Capítulo 2. (si no llegan a terminarlo no se preocupen)

- Arcidiácono y Pererlmiter, [_De bobo, nada_](https://drive.google.com/file/d/1zxUx8VOTSFwTFf5ZVeJNGpL8m_vmlUry/view?usp=sharing), Capítulo 3 "La política de la distancia", 2024.

### Clase 3. Asincrónica (para ver durante las vacaciones)

La evaluación de impacto.

- Banco Mundial y BID, [La evaluación de impacto en la práctica](https://drive.google.com/file/d/1njlFh8NjIVg8lChQcQGoL18JQtGMtRHs/view?usp=sharing), 2016, Capítulo 1.

### Clase 4. 6 de Agosto. Performance Stats

- Robert Behn, [The PerformanceStat Potential](https://drive.google.com/file/d/1ZCK6iXxpFTUZh3X8JFpdhJ1vr4bMytTq/view?usp=sharing), Capítulos 1, 2 y 3.

- Cathy O'Neil, [Weapons of Math Destruction](https://drive.google.com/file/d/10O843_2b8mwYTvTMkqbeOS504tGyaDkG/view?usp=sharing), Capítulo 5.


### Clase 5. 13 de Agosto. Ciencia de Datos — Las funciones básicas

- Vazquez Brust y Zayat, *Ciencia de Datos para el Activismo Jurídico*, [https://cdaj.netlify.app/](https://cdaj.netlify.app/), cap. 1, 2, 3 y 4.

### Clase 6. 20 de Agosto. Ciencia de Datos — Introducción a la Estadística

- Vazquez Brust y Zayat, *Ciencia de Datos para el Activismo Jurídico*, [https://cdaj.netlify.app/](https://cdaj.netlify.app/), cap. 5 y 7.

- Birger Madsen, [Statistics for non-statisticians](https://drive.google.com/file/d/1g87NNdsQ2DKywKzMYNZlBQZzu6Yuv392/view?usp=sharing), capítulo 3: "Descripción de los datos".

### Clase 7. 27 de Agosto. EPH — Paquete EPH — Brecha de género

- Ecofeminita, [La desigualdad de género se puede medir](https://ecofeminita.com/la-desigualdad-de-genero-se-puede-medir/).

- Dirección de Economía, Igualdad y Género, [Las brechas de género en la economía argentina](https://drive.google.com/file/d/1UhrEUJF_S8pYMfW5P44nqr8uIUKEqFg_/view?usp=sharing), 2022.


### Clase 8. 3 de Septiembre. Planificando la IFE

- [Decreto 310/2020](https://servicios.infoleg.gob.ar/infolegInternet/verNorma.do;jsessionid=F5FE38BBBF923D9755A478A64070400C?id=335820)

- Mercedes D'Alessandro, [Ingreso Familiar de Emergencia. Una política pública contrareloj](https://drive.google.com/file/d/1-HrHTgrDJ90c3ISGAEEzhgV5QHUEnyw6/view?usp=sharing)", Fundar, 2022.

- Dictamen INADI sobre [IFE y Migrantes](https://drive.google.com/file/d/1AxCQuTcREFeDa2fIyPhEdhp1QiNG6mOP/view?usp=sharing).

### Clase 9. Asincrónica — Evaluación de impacto del IFE

- Análisis de datos de Covid.


